const state={step:1,service:'Bautizo',duration:'60 min',date:new Date(2026,8,20),time:'09:00'};
const steps=[...document.querySelectorAll('.booking-step')],fill=document.getElementById('progressFill');
function renderStep(){steps.forEach((s,i)=>s.classList.toggle('current-step',i===state.step-1));document.getElementById('stepNumber').textContent=String(state.step).padStart(2,'0');fill.style.width=`${state.step*33.33}%`;document.querySelectorAll('.step-labels span').forEach((x,i)=>x.classList.toggle('current',i===state.step-1));document.getElementById('selectedService').textContent=state.service;document.getElementById('selectedDuration').textContent=state.duration}
document.querySelectorAll('.service').forEach(card=>card.addEventListener('click',()=>{document.querySelectorAll('.service').forEach(x=>x.classList.remove('active'));card.classList.add('active');state.service=card.dataset.service;state.duration=card.dataset.duration;renderStep()}));
document.querySelectorAll('.next-btn').forEach(btn=>btn.addEventListener('click',()=>{if(state.step<3){state.step++;renderStep();document.getElementById('reservar').scrollIntoView({behavior:'smooth',block:'start'})}}));document.querySelectorAll('.back-btn').forEach(btn=>btn.addEventListener('click',()=>{state.step--;renderStep()}));
const monthLabel=document.getElementById('monthLabel'),calendarDays=document.getElementById('calendarDays');
function renderCalendar(){const y=state.date.getFullYear(),m=state.date.getMonth();monthLabel.textContent=new Intl.DateTimeFormat('es-MX',{month:'long',year:'numeric'}).format(state.date);calendarDays.innerHTML='';const first=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate();for(let i=0;i<first;i++){const b=document.createElement('button');b.className='muted';b.disabled=true;calendarDays.appendChild(b)}for(let d=1;d<=days;d++){const b=document.createElement('button');b.textContent=d;const available=(d+first)%7!==0;b.className=available?'available':'';if(d===state.date.getDate()&&m===state.date.getMonth())b.classList.add('selected');if(available)b.addEventListener('click',()=>{state.date=new Date(y,m,d);renderCalendar()});calendarDays.appendChild(b)}}
document.getElementById('prevMonth').addEventListener('click',()=>{state.date.setMonth(state.date.getMonth()-1);renderCalendar()});document.getElementById('nextMonth').addEventListener('click',()=>{state.date.setMonth(state.date.getMonth()+1);renderCalendar()});document.querySelectorAll('.time').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.time').forEach(x=>x.classList.remove('active'));btn.classList.add('active');state.time=btn.textContent}));
document.getElementById('bookingForm').addEventListener('submit',e=>{e.preventDefault();document.getElementById('bookingForm').hidden=true;document.querySelector('.booking-head').hidden=true;document.querySelector('.progress').hidden=true;document.querySelector('.step-labels').hidden=true;document.getElementById('referenceCode').textContent=`RT-2026-${String(Math.floor(Math.random()*900000)+100000)}`;document.getElementById('confirmation').hidden=false});document.getElementById('newBooking').addEventListener('click',()=>location.reload());renderCalendar();renderStep();
